export const EmailSettings = {
    dev: {
        errorMails: ['kezyolanipekun@gmail.com'],
        accountCreateLink: 'http://CP.upltest.com/verify/account/',
        logoutInfoLink: 'http://CP.upltest.com/deactivate/account/',
        mailer: {
            api_key: 'key-bea91471bc2df9be3b75315d4608ae28',
            domain: 'sandbox5ed09b8c84454a49878d8bc53db1d710.mailgun.org',
            host: 'mail.upltest.com',
            port: 587,
            pool: true,
            secure: false,
            from: 'CP <info@payassist.upltest.com>',
            username: 'CP@upltest.com',
            password: 'password123',
        },
        emails: ['kezyolanipekun@gmail.com'],
    },
    test: {
        errorMails: ['kezyolanipekun@gmail.com'],
        accountCreateLink: 'http://CP.upltest.com/verify/account/',
        logoutInfoLink: 'http://CP.upltest.com/deactivate/account/',
        mailer:  {
            api_key: 'key-bea91471bc2df9be3b75315d4608ae28',
            domain: 'sandbox5ed09b8c84454a49878d8bc53db1d710.mailgun.org',
            host: 'mail.upltest.com',
            port: 465,
            pool: true,
            secure: true,
            from: 'CP <info@payassist.upltest.com>',
            username: 'CP@upltest.com',
            password: 'password123',
        },
        emails: ['kezyolanipekun@gmail.com'],
    },
    prod: {
        errorMails: ['kezyolanipekun@gmail.com'],
        accountCreateLink: 'http://CP.upltest.com/verify/account/',
        logoutInfoLink: 'http://CP.upltest.com/deactivate/account/',
        mailer: {
            api_key: 'key-bea91471bc2df9be3b75315d4608ae28',
            domain: 'sandbox5ed09b8c84454a49878d8bc53db1d710.mailgun.org',
            host: 'mail.upltest.com',
            port: 465,
            pool: true,
            secure: true,
            from: 'CP <info@payassist.upltest.com>',
            username: 'CP@upltest.com',
            password: 'password123',
        },
        emails: ['kezyolanipekun@gmail.com'],
    },
};